### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by berty-assistant**

### CODE REVIEW

**Comment by moul** [comment]
Netlify is broken (404 on homepage)

@pierreboc @cdeleeuwe -> can you give a look?

**Comment by moul** [comment]
@cdeleeuwe the build is green (sometimes), but the homepage is 404

we should add a CI test that checks that some pages are not 404:

* /home (home)
* /fr/home (translated home)
* /news (the news category)
* /news/1 (a news)
etc

**Comment by cdeleeuwe** [comment]
> @cdeleeuwe the build is green (sometimes), but the homepage is 404
> 
> we should add a CI test that checks that some pages are not 404:
> 
> * /home (home)
> * /fr/home (translated home)
> * /news (the news category)
> * /news/1 (a news)
>   etc

@moul I just made a PR #308 which checks if all files referenced in the sitemap are generated. If not, it should fail the build.

**Comment by moul** [comment]
Ok Nice! it's just merged; ill close this PR to let Crowdin trigger a new one

**Pull request closed without merging**
