### PR TITLE
Some changes to prepare the website for IPFS

### PR DESCRIPTION
**Pull request by fte378**
Most links are relative links now but there are definitely many left as absolute links.

The biggest problem is the included AMP stylesheet, I think. Hugo doesn't replace URLs in stylesheets with their relative variant, even if the stylesheet is embedded in a web page.
Don't know how to handle this.

### CODE REVIEW

**Comment by moul** [comment]
@cdeleeuwe can you give a look please ?

**Comment by cdeleeuwe** [comment]
@fte378 which AMP stylesheet do you mean? 

For the AMP JS libs, to have valid AMP, it should stay as external links. If this is an issue with IPFS, we could maybe store the JS locally, and make a different build command for each.
For example by using an environment variable, something like:

```
BERTY_IPFS=true hugo --gc
```

Let me know if that makes sense? :)

Bts, minor thing I noticed is that "relativeURLs" was already set in the config.yml file, so now its twice :)

**Comment by fte378** [comment]
@cdeleeuwe  I missed the relativeURLs, sorry :)

Regarding the stlyesheet - I just scanned through the generated files and some amp related stuff was found many times.
I used: `find . -name '*.html' | xargs grep '"/'` in the public folder.

**Comment by fte378** [comment]
Different builds would be no problem I think - if hugo can adjust the JS-links accordingly for different values.

I still have no overview what is all done in the different make targets.  Is there a doc. somewhere?

**Comment by cdeleeuwe** [comment]
@fte378 OK I see. I think only the FontAwesome and Slick fonts are currently using absolute paths. This is because, as you noticed as well, Hugo does not change CSS assets to relative paths :).

Maybe a workaround might be something like described in #37 .

I have made a few issues regarding the items mentioned, including to add some docs regarding the Makefile.

**Comment by cdeleeuwe** [comment]
fyi, just made a PR for the relative CSS assets #39

**Comment by moul** [comment]
I just merged #39, can you rebase this PR against master so we can make a final review?

**Comment by cdeleeuwe** [comment]
@moul I will just make a PR for issue #38 in a bit, then I think it should be ready for IPFS

**Comment by cdeleeuwe** [comment]
Just made the PR.. Once PR #41 is merged, it will serve the AMP libraries with relative paths when building with ```make prod-build-ipfs```

**Comment by moul** [comment]
#41 is merged

**Comment by fte378** [comment]
Ok, I merged the other changes.

**Pull request merged**
