### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by fte378**
If I didn't miss something there is no way to really check the results of website generation.
Generating the website worked for me - please check if all is o.k.

### CODE REVIEW

**Comment by moul** [comment]
Hi @fte378, thank you for this PR,

What do you mean by "check the results"?

If you want to run the website, you can type `make` from the `bertytech/` folder, then open your browser at http://localhost:1313/

**Comment by moul** [comment]
You can also check the `deploy/netlify` link in each PR, for the current one, the link is: https://deploy-preview-25--bertytech.netlify.app/

**Comment by fte378** [comment]
> What do you mean by "check the results"?

I don't have an overview about what is built and how it is built and if any error breaks the build (which should be the case).
So without this knowledge a hugo build without errors doesn't mean that all parts of the site are built correctly. Especially because I changed the tools which are used to do things outside of hugo.

I will have a look at the Makefiles as next step :)

**Comment by fte378** [comment]
Hi @moul ,

I checked that the scripts using the node modules work correctly.

I noticed that there are AMP features used - the AMP-checker spits out lots of problems.
So it's questionable if AMP should be used at all.

I think the PR is ready for merging.

With kind regards,
Frank

**Comment by moul** [comment]
:+1:

Maybe we can setup to push the generated website on a dedicated branch so we can easily get a "git diff" of "what changed"

**Pull request merged**
