### PR TITLE
Change to Lanczos resample filter for blog images

### PR DESCRIPTION
**Pull request by cdeleeuwe**
As discussed in #43

### CODE REVIEW

**Comment by moul** [comment]
@cdeleeuwe is the error due to a build timeout because there is not output during 2 minutes on netlify or something else? because if it's just a "no print during 2 minutes timeout", I can try to hack the script to regularly print "dots" in the logs while the long tasks are running silently

**Comment by cdeleeuwe** [comment]
Hmm, not sure why it throws the error. I can't reproduce this locally. Will try out a few things.

**Comment by cdeleeuwe** [comment]
@moul increasing the timeout seems to solve the issue :)

**Comment by moul** [comment]
@pierreboc you will be able to announce the UI/UX article on twitter in approx 10 minutes :+1:

**Comment by pierreboc** [comment]
Alright

**Pull request merged**
