### PR TITLE
feat: add UX/UI blogpost

### PR DESCRIPTION
**Pull request by alexsland**

### CODE REVIEW

**Comment by alexsland** [comment]
Is there a way to have images in this blogpost not compressed that much ?
It's okay for photos, but app screens are barely readable.

**Comment by moul** [comment]
@cdeleeuwe I think we can tweak the compression config?

**Comment by cdeleeuwe** [comment]
@moul @alexsland , yes I think we can use a higher quality resampling filter (https://github.com/disintegration/imaging). I will give it a try.

**Comment by moul** [comment]
Merging it right now with the current settings

@cdeleeuwe is trying to improve image quality in #45 

We will wait that he finishes before announcing the blogpost on twitter etc

**Pull request merged**
